base_url = "https://posdcast.de/"
title = "Der Posdcast"
description = "Ein Podcast"
default_language = "de"
compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"
